### ISSUE TITLE
Line Breaks in Dialogue 

### ISSUE THREAD

**Issue by hdyla** [dominikmayer/obsidian-yesterday#4]
I quite like the dialogue feature, it's perfect for viewing chatlogs. But there doesn't appear to be line break support for one message, they seem to break everything else instead. Is there any way to add this or am I just doing it wrong?

raw:
![raw](https://github.com/dominikmayer/obsidian-yesterday/assets/6249242/4d1e6726-45dc-436a-83ea-3da6445cd24c)
currently result:
![current result](https://github.com/dominikmayer/obsidian-yesterday/assets/6249242/c4e088c1-0bb0-4534-8fe7-7c7d42369809)
desired: 
![line break desired](https://github.com/dominikmayer/obsidian-yesterday/assets/6249242/6d6004c3-98ee-4e2e-8505-0cbfc8649014)

**Comment by dominikmayer** [comment]
Hi, @hdyla, thanks for writing. I've been struggling with how to properly add support for line breaks. Your example is a simple case as it doesn't contain empty lines. But what about a message like this:

```
.Peter: Have you seen this:

www.something.com
```

How would we know that the line after the empty line is part of the dialog?

I've been thinking about supporting some delimiter like `\\` or `<br>` or `\n`. But this would make the dialog hard to read in edit mode and it wouldn't be easy for people to figure out:

```
.Peter: Have you seen this:\\
\\
www.something.com
```

Or: 

```
.Peter: Have you seen this:\n\nwww.something.com
```

Neither looks appealing.

If anyone has any ideas on how to do it, I'd be very happy to add it. I want this myself. So what I do when I encounter this case is that I switch from a dialog to a quote environment:

```
Peter wrote:

> Have you seen this:
> 
> www.something.com
```

Thinking about it, maybe indentation could work? Like everything indented by at least x spaces would be part of the dialog (not visible, but the empty line would also have two spaces):

```
.Peter: Have you seen this:
  
  www.something.com
```

**Comment by dominikmayer** [comment]
I added support for indented lines.

Because of how Obsidian transforms the text it will also work with unindented lines. This is not going to be supported on the app though and I suggest to indent the lines for readability reasons.

Also because of how Obsidian works my case with the empty lines is not supported.

**Comment by hdyla** [comment]
Wow that was fast! Works perfectly for me, thank you

**Comment by ksdavidc** [comment]
[edit: after posting I realized you meant indenting with tabs, which is not my usual route. I prefer using double spaces since I can see the text better. In that case, how about using a comma or semicolon to create the empty lines. This aligns with the "." dot syntax, rarely appear at the start of a line, and are only one character as opposed to //.]

Nice plugin. I especially like that it doesn't require using codeblocks to get the effect. 

Indented lines do not seem to be working for me. Unindented in obsidian does not seem to work.
Screenshots from sandbox vault (with show whitespace plugin). Am I doing it wrong? 
<img width="283" alt="Screenshot 2024-08-07 at 8 10 30 AM" src="https://github.com/user-attachments/assets/f394e254-4f08-4e52-9c81-78df6d6a6c42">
<img width="277" alt="Screenshot 2024-08-07 at 8 10 38 AM" src="https://github.com/user-attachments/assets/e4269072-fb11-4864-ac50-591f98e427a1">

One, not perfect, workaround is to use invisible spaces, with obvious drawbacks (not visible).

Also, while we are at it, why not a preview mode? Switching to reading mode when drafting less than optimal.

Also, can we have another way to identify text that goes on the right other than using me? Why not ","?

**Comment by dominikmayer** [comment]
You can use spaces, you don't need tabs.

Because of how Obsidian works empty lines will break the dialog. Workaround would be putting a dot in the empty line.

What would be a use-case of where you would have a conversation that does not involve you and you would like to define which speaker is on the right?
